### ISSUE TITLE
Can the Ad-RSS-lib be used/integrate with other simulators like LGSVL/ROS world

### ISSUE THREAD

**Issue by vivekgourav** [intel/ad-rss-lib#102]
Can the Ad-rss-lib be used in a different environment other than carla?

**Comment by berndgassmann** [comment]
Sure, the library is not directly connected to CARLA.

1. The ad_rss library is designed to be even completely independent from an actual map representation.
2. The ad_rss_map_integration library is demonstrating a possibility on how on could derive the required input to RSS based on vehicle states and underlying map data. For this, the ad_map_access library is used which is published under [the github carla project](https://ad-map-access.readthedocs.io/en/latest/). But also that map library is completely independent from CARLA simulator itself -- it's just reusing the OpenDRIVE reader code from CARLA. Some tools around [OpenSCENARIO creation/editing](https://github.com/carla-simulator/traffic-generation-editor) are also relying on that ad_map_access library.

The only tight connection to CARLA is the actual integration of the [RSS Sensor](https://carla.readthedocs.io/en/0.9.11/adv_rss/) within CARLA which makes use of the libraries from with ad-rss-lib.
