### ISSUE TITLE
Is it possible to use ad-rss-lib with only LiDAR as an input?

### ISSUE THREAD

**Issue by vivekgourav** [intel/ad-rss-lib#104]
Since the input to the world model is sensor information & AD Map data.  (For eg: Can Gazebo models be used?)
Also, what are the steps for integration of ad-rss-lib outside of CARLA using Ad_map_access?

**Comment by berndgassmann** [comment]
Hi,

the input to the world model is in general object data; where this data is derived from is not specified. One can extract the data from internal simulator ground truth data (as e.g. done within the RssSensor integrated into CARLA), derive from processed sensor measurements, or from any other reliable data source. 
The information required when using ad_rss_map_integration functionality is mainly defined by the [RssObjectData](https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/impl/include/ad/rss/map/RssObjectData.hpp) struct which is passed to the functions in [RssSceneCreation](https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/impl/include/ad/rss/map/RssSceneCreation.hpp).
The [unit tests](https://github.com/intel/ad-rss-lib/tree/master/ad_rss_map_integration/impl/tests) provide some simple examples. You mainly need:

- map data of your environment in a form that ad_map_access can load it (e.g. an OpenDRIVE map)
- need to know/calculate the position, dimensions and dynamics of the vehicles you want to consider and perform [map matching](https://github.com/carla-simulator/map/blob/master/ad_map_access/impl/include/ad/map/match/AdMapMatching.hpp) on it to relate it in the map to fill the ::ad::map::match::Object data of RssObjectData
- if traffic lights are relevant for the scenes, the state of the traffic lights is required to calculate the right of way correctly
- you can restrict the calculations on a certain intended route of the ego-vehicle, if you know it upfront and feed it into [RssSceneCreation::appendScenes()](https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/impl/include/ad/rss/map/RssSceneCreation.hpp#L120)
- and you have to select the ::ad::rss::world::RssDynamics and the ::ad::rss::map::RssMode you want to use for the calculations

These are the main steps, I'd say.
