### ISSUE TITLE
cmake ad_physics error

### ISSUE THREAD

**Issue by ccplxx** [intel/ad-rss-lib#107]
when I do "cmake ../../dependencies/map/ad_physics -DCMAKE_INSTALL_PREFIX=../../install/ad_physics -DCMAKE_PREFIX_PATH=../../install/spdlog"
But, 
CMake Error at generated/CMakeLists.txt:34 (find_package):
  Could not find a package configuration file provided by "spdlog" with any
  of the following names:

    spdlogConfig.cmake
    spdlog-config.cmake

  Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
  "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
  provides a separate development package or SDK, be sure it has been
  installed.
How to fix this problem, thanks

**Comment by berndgassmann** [comment]
hmm, can you check if spdlog was built correctly? I mean the folder at ../../install/spdlog should contain the installed content from the build of spdlog beforehand. I.e. the cmake file should be there in a way like e.g.:

── lib
│   ├── cmake
│   │   └── spdlog
│   │       ├── spdlogConfig.cmake
│   │       ├── spdlogConfigTargets.cmake
│   │       ├── spdlogConfigTargets-release.cmake
│   │       └── spdlogConfigVersion.cmake
│   ├── libspdlog.a
│   └── pkgconfig
│       └── spdlog.pc

Best is to make use of colcon to build; that makes it much much much much easier, as it is only one single command in the end.
