### ISSUE TITLE
"×××××× spdlog.cpp.o"can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by chenhengwei1999** [intel/ad-rss-lib#120]
I'm executing the make command in the ~/map/ad_physics/build folder, and  i have some errors below:

-------
/usr/bin/ld: /usr/local/lib/libspdlog.a(spdlog.cpp.o): relocation R_X86_64_TPOFF32 against `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ad_physics.dir/build.make:295: libad_physics.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ad_physics.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
-------

I found a similar solution in this URL-https://blog.csdn.net/u010333076/article/details/77227552
but i doesn't match my questions.

The Makefile in the ~/map/ad_physics/build/Makefile is below:

-------
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chw/projects/clion_code/carla_RSS_Build/map/ad_physics

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chw/projects/clion_code/carla_RSS_Build/map/ad_physics/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chw/projects/clion_code/carla_RSS_Build/map/ad_physics/build/CMakeFiles /home/chw/projects/clion_code/carla_RSS_Build/map/ad_physics/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chw/projects/clion_code/carla_RSS_Build/map/ad_physics/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ad_physics

# Build rule for target.
ad_physics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ad_physics
.PHONY : ad_physics

# fast build rule for target.
ad_physics/fast:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/build
.PHONY : ad_physics/fast

generated/src/ad/physics/Acceleration.o: generated/src/ad/physics/Acceleration.cpp.o

.PHONY : generated/src/ad/physics/Acceleration.o

# target to build an object file
generated/src/ad/physics/Acceleration.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Acceleration.cpp.o
.PHONY : generated/src/ad/physics/Acceleration.cpp.o

generated/src/ad/physics/Acceleration.i: generated/src/ad/physics/Acceleration.cpp.i

.PHONY : generated/src/ad/physics/Acceleration.i

# target to preprocess a source file
generated/src/ad/physics/Acceleration.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Acceleration.cpp.i
.PHONY : generated/src/ad/physics/Acceleration.cpp.i

generated/src/ad/physics/Acceleration.s: generated/src/ad/physics/Acceleration.cpp.s

.PHONY : generated/src/ad/physics/Acceleration.s

# target to generate assembly for a file
generated/src/ad/physics/Acceleration.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Acceleration.cpp.s
.PHONY : generated/src/ad/physics/Acceleration.cpp.s

generated/src/ad/physics/Angle.o: generated/src/ad/physics/Angle.cpp.o

.PHONY : generated/src/ad/physics/Angle.o

# target to build an object file
generated/src/ad/physics/Angle.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Angle.cpp.o
.PHONY : generated/src/ad/physics/Angle.cpp.o

generated/src/ad/physics/Angle.i: generated/src/ad/physics/Angle.cpp.i

.PHONY : generated/src/ad/physics/Angle.i

# target to preprocess a source file
generated/src/ad/physics/Angle.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Angle.cpp.i
.PHONY : generated/src/ad/physics/Angle.cpp.i

generated/src/ad/physics/Angle.s: generated/src/ad/physics/Angle.cpp.s

.PHONY : generated/src/ad/physics/Angle.s

# target to generate assembly for a file
generated/src/ad/physics/Angle.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Angle.cpp.s
.PHONY : generated/src/ad/physics/Angle.cpp.s

generated/src/ad/physics/AngularAcceleration.o: generated/src/ad/physics/AngularAcceleration.cpp.o

.PHONY : generated/src/ad/physics/AngularAcceleration.o

# target to build an object file
generated/src/ad/physics/AngularAcceleration.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularAcceleration.cpp.o
.PHONY : generated/src/ad/physics/AngularAcceleration.cpp.o

generated/src/ad/physics/AngularAcceleration.i: generated/src/ad/physics/AngularAcceleration.cpp.i

.PHONY : generated/src/ad/physics/AngularAcceleration.i

# target to preprocess a source file
generated/src/ad/physics/AngularAcceleration.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularAcceleration.cpp.i
.PHONY : generated/src/ad/physics/AngularAcceleration.cpp.i

generated/src/ad/physics/AngularAcceleration.s: generated/src/ad/physics/AngularAcceleration.cpp.s

.PHONY : generated/src/ad/physics/AngularAcceleration.s

# target to generate assembly for a file
generated/src/ad/physics/AngularAcceleration.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularAcceleration.cpp.s
.PHONY : generated/src/ad/physics/AngularAcceleration.cpp.s

generated/src/ad/physics/AngularVelocity.o: generated/src/ad/physics/AngularVelocity.cpp.o

.PHONY : generated/src/ad/physics/AngularVelocity.o

# target to build an object file
generated/src/ad/physics/AngularVelocity.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularVelocity.cpp.o
.PHONY : generated/src/ad/physics/AngularVelocity.cpp.o

generated/src/ad/physics/AngularVelocity.i: generated/src/ad/physics/AngularVelocity.cpp.i

.PHONY : generated/src/ad/physics/AngularVelocity.i

# target to preprocess a source file
generated/src/ad/physics/AngularVelocity.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularVelocity.cpp.i
.PHONY : generated/src/ad/physics/AngularVelocity.cpp.i

generated/src/ad/physics/AngularVelocity.s: generated/src/ad/physics/AngularVelocity.cpp.s

.PHONY : generated/src/ad/physics/AngularVelocity.s

# target to generate assembly for a file
generated/src/ad/physics/AngularVelocity.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/AngularVelocity.cpp.s
.PHONY : generated/src/ad/physics/AngularVelocity.cpp.s

generated/src/ad/physics/Distance.o: generated/src/ad/physics/Distance.cpp.o

.PHONY : generated/src/ad/physics/Distance.o

# target to build an object file
generated/src/ad/physics/Distance.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Distance.cpp.o
.PHONY : generated/src/ad/physics/Distance.cpp.o

generated/src/ad/physics/Distance.i: generated/src/ad/physics/Distance.cpp.i

.PHONY : generated/src/ad/physics/Distance.i

# target to preprocess a source file
generated/src/ad/physics/Distance.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Distance.cpp.i
.PHONY : generated/src/ad/physics/Distance.cpp.i

generated/src/ad/physics/Distance.s: generated/src/ad/physics/Distance.cpp.s

.PHONY : generated/src/ad/physics/Distance.s

# target to generate assembly for a file
generated/src/ad/physics/Distance.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Distance.cpp.s
.PHONY : generated/src/ad/physics/Distance.cpp.s

generated/src/ad/physics/DistanceSquared.o: generated/src/ad/physics/DistanceSquared.cpp.o

.PHONY : generated/src/ad/physics/DistanceSquared.o

# target to build an object file
generated/src/ad/physics/DistanceSquared.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DistanceSquared.cpp.o
.PHONY : generated/src/ad/physics/DistanceSquared.cpp.o

generated/src/ad/physics/DistanceSquared.i: generated/src/ad/physics/DistanceSquared.cpp.i

.PHONY : generated/src/ad/physics/DistanceSquared.i

# target to preprocess a source file
generated/src/ad/physics/DistanceSquared.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DistanceSquared.cpp.i
.PHONY : generated/src/ad/physics/DistanceSquared.cpp.i

generated/src/ad/physics/DistanceSquared.s: generated/src/ad/physics/DistanceSquared.cpp.s

.PHONY : generated/src/ad/physics/DistanceSquared.s

# target to generate assembly for a file
generated/src/ad/physics/DistanceSquared.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DistanceSquared.cpp.s
.PHONY : generated/src/ad/physics/DistanceSquared.cpp.s

generated/src/ad/physics/Duration.o: generated/src/ad/physics/Duration.cpp.o

.PHONY : generated/src/ad/physics/Duration.o

# target to build an object file
generated/src/ad/physics/Duration.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Duration.cpp.o
.PHONY : generated/src/ad/physics/Duration.cpp.o

generated/src/ad/physics/Duration.i: generated/src/ad/physics/Duration.cpp.i

.PHONY : generated/src/ad/physics/Duration.i

# target to preprocess a source file
generated/src/ad/physics/Duration.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Duration.cpp.i
.PHONY : generated/src/ad/physics/Duration.cpp.i

generated/src/ad/physics/Duration.s: generated/src/ad/physics/Duration.cpp.s

.PHONY : generated/src/ad/physics/Duration.s

# target to generate assembly for a file
generated/src/ad/physics/Duration.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Duration.cpp.s
.PHONY : generated/src/ad/physics/Duration.cpp.s

generated/src/ad/physics/DurationSquared.o: generated/src/ad/physics/DurationSquared.cpp.o

.PHONY : generated/src/ad/physics/DurationSquared.o

# target to build an object file
generated/src/ad/physics/DurationSquared.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DurationSquared.cpp.o
.PHONY : generated/src/ad/physics/DurationSquared.cpp.o

generated/src/ad/physics/DurationSquared.i: generated/src/ad/physics/DurationSquared.cpp.i

.PHONY : generated/src/ad/physics/DurationSquared.i

# target to preprocess a source file
generated/src/ad/physics/DurationSquared.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DurationSquared.cpp.i
.PHONY : generated/src/ad/physics/DurationSquared.cpp.i

generated/src/ad/physics/DurationSquared.s: generated/src/ad/physics/DurationSquared.cpp.s

.PHONY : generated/src/ad/physics/DurationSquared.s

# target to generate assembly for a file
generated/src/ad/physics/DurationSquared.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/DurationSquared.cpp.s
.PHONY : generated/src/ad/physics/DurationSquared.cpp.s

generated/src/ad/physics/ParametricValue.o: generated/src/ad/physics/ParametricValue.cpp.o

.PHONY : generated/src/ad/physics/ParametricValue.o

# target to build an object file
generated/src/ad/physics/ParametricValue.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/ParametricValue.cpp.o
.PHONY : generated/src/ad/physics/ParametricValue.cpp.o

generated/src/ad/physics/ParametricValue.i: generated/src/ad/physics/ParametricValue.cpp.i

.PHONY : generated/src/ad/physics/ParametricValue.i

# target to preprocess a source file
generated/src/ad/physics/ParametricValue.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/ParametricValue.cpp.i
.PHONY : generated/src/ad/physics/ParametricValue.cpp.i

generated/src/ad/physics/ParametricValue.s: generated/src/ad/physics/ParametricValue.cpp.s

.PHONY : generated/src/ad/physics/ParametricValue.s

# target to generate assembly for a file
generated/src/ad/physics/ParametricValue.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/ParametricValue.cpp.s
.PHONY : generated/src/ad/physics/ParametricValue.cpp.s

generated/src/ad/physics/Probability.o: generated/src/ad/physics/Probability.cpp.o

.PHONY : generated/src/ad/physics/Probability.o

# target to build an object file
generated/src/ad/physics/Probability.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Probability.cpp.o
.PHONY : generated/src/ad/physics/Probability.cpp.o

generated/src/ad/physics/Probability.i: generated/src/ad/physics/Probability.cpp.i

.PHONY : generated/src/ad/physics/Probability.i

# target to preprocess a source file
generated/src/ad/physics/Probability.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Probability.cpp.i
.PHONY : generated/src/ad/physics/Probability.cpp.i

generated/src/ad/physics/Probability.s: generated/src/ad/physics/Probability.cpp.s

.PHONY : generated/src/ad/physics/Probability.s

# target to generate assembly for a file
generated/src/ad/physics/Probability.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Probability.cpp.s
.PHONY : generated/src/ad/physics/Probability.cpp.s

generated/src/ad/physics/RatioValue.o: generated/src/ad/physics/RatioValue.cpp.o

.PHONY : generated/src/ad/physics/RatioValue.o

# target to build an object file
generated/src/ad/physics/RatioValue.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/RatioValue.cpp.o
.PHONY : generated/src/ad/physics/RatioValue.cpp.o

generated/src/ad/physics/RatioValue.i: generated/src/ad/physics/RatioValue.cpp.i

.PHONY : generated/src/ad/physics/RatioValue.i

# target to preprocess a source file
generated/src/ad/physics/RatioValue.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/RatioValue.cpp.i
.PHONY : generated/src/ad/physics/RatioValue.cpp.i

generated/src/ad/physics/RatioValue.s: generated/src/ad/physics/RatioValue.cpp.s

.PHONY : generated/src/ad/physics/RatioValue.s

# target to generate assembly for a file
generated/src/ad/physics/RatioValue.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/RatioValue.cpp.s
.PHONY : generated/src/ad/physics/RatioValue.cpp.s

generated/src/ad/physics/Speed.o: generated/src/ad/physics/Speed.cpp.o

.PHONY : generated/src/ad/physics/Speed.o

# target to build an object file
generated/src/ad/physics/Speed.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Speed.cpp.o
.PHONY : generated/src/ad/physics/Speed.cpp.o

generated/src/ad/physics/Speed.i: generated/src/ad/physics/Speed.cpp.i

.PHONY : generated/src/ad/physics/Speed.i

# target to preprocess a source file
generated/src/ad/physics/Speed.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Speed.cpp.i
.PHONY : generated/src/ad/physics/Speed.cpp.i

generated/src/ad/physics/Speed.s: generated/src/ad/physics/Speed.cpp.s

.PHONY : generated/src/ad/physics/Speed.s

# target to generate assembly for a file
generated/src/ad/physics/Speed.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Speed.cpp.s
.PHONY : generated/src/ad/physics/Speed.cpp.s

generated/src/ad/physics/SpeedSquared.o: generated/src/ad/physics/SpeedSquared.cpp.o

.PHONY : generated/src/ad/physics/SpeedSquared.o

# target to build an object file
generated/src/ad/physics/SpeedSquared.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/SpeedSquared.cpp.o
.PHONY : generated/src/ad/physics/SpeedSquared.cpp.o

generated/src/ad/physics/SpeedSquared.i: generated/src/ad/physics/SpeedSquared.cpp.i

.PHONY : generated/src/ad/physics/SpeedSquared.i

# target to preprocess a source file
generated/src/ad/physics/SpeedSquared.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/SpeedSquared.cpp.i
.PHONY : generated/src/ad/physics/SpeedSquared.cpp.i

generated/src/ad/physics/SpeedSquared.s: generated/src/ad/physics/SpeedSquared.cpp.s

.PHONY : generated/src/ad/physics/SpeedSquared.s

# target to generate assembly for a file
generated/src/ad/physics/SpeedSquared.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/SpeedSquared.cpp.s
.PHONY : generated/src/ad/physics/SpeedSquared.cpp.s

generated/src/ad/physics/Weight.o: generated/src/ad/physics/Weight.cpp.o

.PHONY : generated/src/ad/physics/Weight.o

# target to build an object file
generated/src/ad/physics/Weight.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Weight.cpp.o
.PHONY : generated/src/ad/physics/Weight.cpp.o

generated/src/ad/physics/Weight.i: generated/src/ad/physics/Weight.cpp.i

.PHONY : generated/src/ad/physics/Weight.i

# target to preprocess a source file
generated/src/ad/physics/Weight.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Weight.cpp.i
.PHONY : generated/src/ad/physics/Weight.cpp.i

generated/src/ad/physics/Weight.s: generated/src/ad/physics/Weight.cpp.s

.PHONY : generated/src/ad/physics/Weight.s

# target to generate assembly for a file
generated/src/ad/physics/Weight.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/generated/src/ad/physics/Weight.cpp.s
.PHONY : generated/src/ad/physics/Weight.cpp.s

src/Operation.o: src/Operation.cpp.o

.PHONY : src/Operation.o

# target to build an object file
src/Operation.cpp.o:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/src/Operation.cpp.o
.PHONY : src/Operation.cpp.o

src/Operation.i: src/Operation.cpp.i

.PHONY : src/Operation.i

# target to preprocess a source file
src/Operation.cpp.i:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/src/Operation.cpp.i
.PHONY : src/Operation.cpp.i

src/Operation.s: src/Operation.cpp.s

.PHONY : src/Operation.s

# target to generate assembly for a file
src/Operation.cpp.s:
	$(MAKE) -f CMakeFiles/ad_physics.dir/build.make CMakeFiles/ad_physics.dir/src/Operation.cpp.s
.PHONY : src/Operation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ad_physics"
	@echo "... generated/src/ad/physics/Acceleration.o"
	@echo "... generated/src/ad/physics/Acceleration.i"
	@echo "... generated/src/ad/physics/Acceleration.s"
	@echo "... generated/src/ad/physics/Angle.o"
	@echo "... generated/src/ad/physics/Angle.i"
	@echo "... generated/src/ad/physics/Angle.s"
	@echo "... generated/src/ad/physics/AngularAcceleration.o"
	@echo "... generated/src/ad/physics/AngularAcceleration.i"
	@echo "... generated/src/ad/physics/AngularAcceleration.s"
	@echo "... generated/src/ad/physics/AngularVelocity.o"
	@echo "... generated/src/ad/physics/AngularVelocity.i"
	@echo "... generated/src/ad/physics/AngularVelocity.s"
	@echo "... generated/src/ad/physics/Distance.o"
	@echo "... generated/src/ad/physics/Distance.i"
	@echo "... generated/src/ad/physics/Distance.s"
	@echo "... generated/src/ad/physics/DistanceSquared.o"
	@echo "... generated/src/ad/physics/DistanceSquared.i"
	@echo "... generated/src/ad/physics/DistanceSquared.s"
	@echo "... generated/src/ad/physics/Duration.o"
	@echo "... generated/src/ad/physics/Duration.i"
	@echo "... generated/src/ad/physics/Duration.s"
	@echo "... generated/src/ad/physics/DurationSquared.o"
	@echo "... generated/src/ad/physics/DurationSquared.i"
	@echo "... generated/src/ad/physics/DurationSquared.s"
	@echo "... generated/src/ad/physics/ParametricValue.o"
	@echo "... generated/src/ad/physics/ParametricValue.i"
	@echo "... generated/src/ad/physics/ParametricValue.s"
	@echo "... generated/src/ad/physics/Probability.o"
	@echo "... generated/src/ad/physics/Probability.i"
	@echo "... generated/src/ad/physics/Probability.s"
	@echo "... generated/src/ad/physics/RatioValue.o"
	@echo "... generated/src/ad/physics/RatioValue.i"
	@echo "... generated/src/ad/physics/RatioValue.s"
	@echo "... generated/src/ad/physics/Speed.o"
	@echo "... generated/src/ad/physics/Speed.i"
	@echo "... generated/src/ad/physics/Speed.s"
	@echo "... generated/src/ad/physics/SpeedSquared.o"
	@echo "... generated/src/ad/physics/SpeedSquared.i"
	@echo "... generated/src/ad/physics/SpeedSquared.s"
	@echo "... generated/src/ad/physics/Weight.o"
	@echo "... generated/src/ad/physics/Weight.i"
	@echo "... generated/src/ad/physics/Weight.s"
	@echo "... src/Operation.o"
	@echo "... src/Operation.i"
	@echo "... src/Operation.s"
.PHONY : help

#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
--------

I don't know how to resolve this problem, Anyone can help me? Thanks A LOT ~

**Comment by berndgassmann** [comment]
Hi looks like the spdlog library that the linker is trying to use under /usr/local/lib/libspdlog.a is not compiled with -fPIC flag in your case. When compiling spdlog this flag has to be enabled.
In the colcon configuration
https://github.com/intel/ad-rss-lib/blob/master/colcon.meta
the cmake argument for position independent code is getting activated:
`-DCMAKE_POSITION_INDEPENDENT_CODE=ON`

So the solution is to recompile the libspdlog.a with the `-fPIC` compiler flag active.
Most probably you did not build spdlog using colcon. When you compiled it directly using cmake you can just activate the flag with the above cmake definition.

**Comment by chenhengwei1999** [comment]
> Hi looks like the spdlog library that the linker is trying to use under /usr/local/lib/libspdlog.a is not compiled with -fPIC flag in your case. When compiling spdlog this flag has to be enabled. In the colcon configuration https://github.com/intel/ad-rss-lib/blob/master/colcon.meta the cmake argument for position independent code is getting activated: `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`
> 
> So the solution is to recompile the libspdlog.a with the `-fPIC` compiler flag active. Most probably you did not build spdlog using colcon. When you compiled it directly using cmake you can just activate the flag with the above cmake definition.

My problem has been solved. Thank you very much!

**Comment by varunjammula** [comment]
@chenhengwei1999 How did you solve this?
