### ISSUE TITLE
RSS Sensor crashes Carla Simulator-0.9.13

### ISSUE THREAD

**Issue by dejavu9127** [intel/ad-rss-lib#128]
Hi, I am repeatedly getting following error when using RSS Sensor with Carla-0.9.13

```powershell
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)
````

I suspect this might be due to call `vehicle.get_physics_control()` in RSS python implementation, since it makes a request to server causing it to crash.

**Comment by berndgassmann** [comment]
Do you still have problems on this? You don't have to call the get_physics_control() every cycle; in the example code in CARLA we also call it only once and pass the control to the restrictor function.

**Comment by dejavu9127** [comment]
@berndgassmann . Thanks, the issue is resolved.
