### ISSUE TITLE
Clang-format update

### ISSUE THREAD

**Issue by adamkrawczyk** [intel/ad-rss-lib#130]
There are differences in formatting across clang-format versions (10 vs 14). 

Since clang-format ver 10 is not available by default in `Ubuntu 22` the suggestion is to bump CI and instruction version to `clang-format-14` or ver `12` (by default in Ubuntu 20). 

Or should we stick to the ver 10? 

I can post a PR with ver 14.

**Comment by berndgassmann** [comment]
Sure, we can switch to clang-format-14.
Appreciate your PR.
