### ISSUE TITLE
Unclear usage in the python example

### ISSUE THREAD

**Issue by DPeled** [intel/ad-rss-lib#134]
Hi, on the python example in `ad_rss/python/tests/interface_test.py` at line [108](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/python/tests/interface_test.py#L108) the value passed to the brakeMin is negative while in the [doxygen documentation](https://intel.github.io/ad-rss-lib/doxygen/ad_rss/structad_1_1rss_1_1world_1_1LateralRssAccelerationValues.html#a4c90c88c445ebe9702c21a793d940745) said the value has to be positive. Is this mistake on purpose?

**Comment by berndgassmann** [comment]
Sorry, but on this the doxygen documentation is outdated. At some point in time the behavior was adapted, but the doxygen documentation was not. The brake values have to be negative to be accepted. See also the input check on [longitudinal](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/generated/include/ad/rss/world/LongitudinalRssAccelerationValuesValidInputRange.hpp) and [lateral](https://github.com/intel/ad-rss-lib/blob/master/ad_rss/generated/include/ad/rss/world/LateralRssAccelerationValuesValidInputRange.hpp) input ranges.
So indeed a mistake.
