### ISSUE TITLE
complie failure

### ISSUE THREAD

**Issue by xmuchen** [intel/ad-rss-lib#136]
When I execute the following command
```
git clone https://github.com/intel/ad-rss-lib.git
cd ad-rss-lib
git submodule update --init
colcon build
```

This error occurred

![企业微信截图_20231024191425](https://github.com/intel/ad-rss-lib/assets/122765896/82b14438-6f25-41ab-9a0f-4be06c67a621)

Please help me look at the problem

**Comment by fabianoboril** [comment]
Hi,
please try to use "git submodule update --init --recursive". It seems like a part of the submodules are missing.

**Comment by berndgassmann** [comment]
problem should be solved.
