### ISSUE TITLE
Errors Colcon Building ad-rss-lib

### ISSUE THREAD

**Issue by Anhar2** [intel/ad-rss-lib#192]
Hi,

I'm trying to install and build the library to be used by the RSS module withing CARLA

I'm using CARLA version 14 for leaderboard on Ubuntu 20 Focal Fossa

First, the cloning using the terminal kept aborting with error RPC failed, so I had to download it as a ZIP file

Second, when I build and reach the colcon build -metas colcon_python.meta, I end up with this error

I installed ad_physics already, and don't know what to do with either it or the carlaviz-backend

colcon build --metas colcon_python.meta
Starting >>> carla_msgs
Starting >>> ros_compatibility             
Starting >>> carla_common                                  
Starting >>> carla_ros_scenario_runner_types               
Starting >>> carla_waypoint_types                          
Starting >>> ad_rss                                        
Starting >>> carla_twist_to_control                        
Starting >>> gstreaming                                    
Starting >>> telecarla_msgs                                
Starting >>> carlaviz-backend                              
Starting >>> pandacan                                       
Starting >>> rqt_carla_control                              
--- stderr: ad_rss                                                      
CMake Error at CMakeLists.txt:33 (find_package):
  Could not find a package configuration file provided by "ad_physics"
  (requested version 2.6.3) with any of the following names:

    ad_physicsConfig.cmake
    ad_physics-config.cmake

  Add the installation prefix of "ad_physics" to CMAKE_PREFIX_PATH or set
  "ad_physics_DIR" to a directory containing one of the above files.  If
  "ad_physics" provides a separate development package or SDK, be sure it has
  been installed.

---
Failed   <<< ad_rss [8.94s, exited with code 1]
--- stderr: carlaviz-backend
CMake Error at CMakeLists.txt:14 (include):
  include could not find load file:

    third_party/LibCarla/cmake/CMakeLists.txt.in

---
Failed   <<< carlaviz-backend [6.71s, exited with code 1]
Aborted  <<< ros_compatibility [11.3s]
Aborted  <<< carla_common [10.6s]
Aborted  <<< carla_twist_to_control [8.41s]
Aborted  <<< pandacan [6.18s]
Aborted  <<< rqt_carla_control [5.66s]
Aborted  <<< telecarla_msgs [7.23s]
Aborted  <<< gstreaming [7.76s]
Aborted  <<< carla_msgs [11.8s]
Aborted  <<< carla_ros_scenario_runner_types [11.7s]
Aborted  <<< carla_waypoint_types [11.4s]                                    

Summary: 0 packages finished [24.9s]
  2 packages failed: ad_rss carlaviz-backend
  10 packages aborted: carla_common carla_msgs carla_ros_scenario_runner_types carla_twist_to_control carla_waypoint_types gstreaming pandacan ros_compatibility rqt_carla_control telecarla_msgs
  4 packages had stderr output: ad_rss carlaviz-backend gstreaming telecarla_msgs
  17 packages not processed

-----------------

Thank you

**Comment by berndgassmann** [comment]
it looks as if the ad_physics is missing therefore the git submodule dependencies of ad-rss-lib seems not to be checked out. Try to go to ad-rss-lib folder and perform a:
git submodule update --init --recursive
that should checkout ad-map-access (which is github.com/carla-simulator/map) and the recursive flag should checkout the dependencies that map requires.

**Comment by Anhar2** [comment]
> it looks as if the ad_physics is missing therefore the git submodule dependencies of ad-rss-lib seems not to be checked out. Try to go to ad-rss-lib folder and perform a: git submodule update --init --recursive that should checkout ad-map-access (which is github.com/carla-simulator/map) and the recursive flag should checkout the dependencies that map requires.

After your reply, I built ad-map-access independently first, I am not sure whether this is what you menat, but I think the issue was solved once I could clone the ad-lib-rss repo not just download as ZIP, then it was built successfully, thank you!
