### ISSUE TITLE
rss library compilation error 

### ISSUE THREAD

**Issue by l1212s** [intel/ad-rss-lib#4]
sudo apt-get install git build-essential cmake libgtest-dev
git clone https://github.com/intel/ad-rss-lib . 
cd ad-rss-lib 
mkdir build
cd build 
cmake .. 
make 
...
/usr/bin/ld: /usr/local/lib/libgtest_main.a(gtest_main.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgtest_main.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/CMakeFiles/ad_rss_tests.dir/build.make:2333: recipe for target 'tests/ad_rss_tests' failed
make[2]: *** [tests/ad_rss_tests] Error 1
CMakeFiles/Makefile2:122: recipe for target 'tests/CMakeFiles/ad_rss_tests.dir/all' failed
make[1]: *** [tests/CMakeFiles/ad_rss_tests.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by berndgassmann** [comment]
The compilation failed, because gtest is linked static and is not compiled with the same compiler flags than the RSS sources. Usually one should not use pre-compiled gtest binaries.
But to make life easier and increase compatibility, we decided to disable i.e. hardening build flags by default.
