### ISSUE TITLE
Guide to get started 

### ISSUE THREAD

**Issue by likui01** [intel/ad-rss-lib#49]
HI, 
I would like to use this library with Carla simulator.
Is there any tutorial to guide how to integrate RSS lib with Carla and run a simple example?

**Comment by berndgassmann** [comment]
Hi.

Interesting that you ask this question. Maybe you have a look at the pull request open at CARLA side which provides a basic form of integration into CARLA:
https://github.com/carla-simulator/carla/pull/1935

With that it is possible to look at simulated situations -- at least if the situation with the other vehicle is within the same CARLA road segment. The basic implementation is not supporting multiple road segments, but we are working on a more general solution based on the open drive map...

**Comment by vivekgourav** [comment]
Hi ,
I am curious to know if RSS lib can be used alongside Autoware.ai as a safety layer in CARLA simulator. ?
If so how can it be achieved?

**Comment by berndgassmann** [comment]
Hi,

the best current option is to use the RSS Sensor integrated into CARLA.

http://carla.org/2020/06/09/talks_2020/
In the CARLA talks from last year you find slides on CARLA<->ROS<->Autoware and also some slides on the "Integration of RSS-lib".

There is also a 10min talk on the CARLA integration from last years SafeComp WAISE workshop on our paper:
"Integration of formal safety models on system level using the example of responsibility sensitive safety and CARLA driving simulator" to give some detailed explanation of the architecture of the integration into CARLA
https://www.youtube.com/watch?v=ecbG3bvk49k&list=PL8BDQqihcOCh2EdaDdp8ZBEsf9X3VgETC&index=7

Furthermore, there is the documentation section in CARLA:
https://carla.readthedocs.io/en/0.9.11/adv_rss/
including the PythonAPI for the virtual RSS-Sensor
https://carla.readthedocs.io/en/0.9.11/python_api/#carla.RssSensor

The example python code on how the RSS Sensor can be addressed from python is here:
https://github.com/carla-simulator/carla/tree/master/PythonAPI/examples/rss

The RSS check results then can be used to restrict the Autoware control output if desired -- or only used to evaluate the safety measures of the Autoware.ai stack in general without restricting the control.
Some words on the restriction functionality:
Maybe for the first shot in the super-simple form as implemented in the CARLA RSS restrictor. 
But in the mid term to e.g. resample the calculated trajectory in such a way, that the trajectory complies with the RSS acceleration restrictions -- which in general provide boundaries for the accelerations of the vehicle in longitudinal/lateral direction in respect to the respective route -- ALL the time (not only when situations are getting dangerous). For a more realistic setup, this is required to enforce that the trajectory of the vehicle is not exceeding the nominal area of the movement model which is inserted into the calculation via the RSS-Parameters. Like this, the ego-vehicle can be prevented from e.g. braking harder or accelerate faster than the borders which are used to compute the safety envelope around the ego vehicle.

Hope this helps for getting started.
Bernd.

**Comment by vivekgourav** [comment]
Thanks @berndgassmann 

The information provided was quite helpful in understanding the usage of RSS as a safety envelop in the Autoware stack.

I am looking forward to implementing an RSS restrictor that mainly provides vehicle's acc/dec/steering boundaries and resamples the output from autoware vehicle commands inside the CARLA simulator.
