### ISSUE TITLE
Reference to any repo where rss with python binding is used 

### ISSUE THREAD

**Issue by tvsrr** [intel/ad-rss-lib#75]
Hello. Is there any repository where ad-rss-lib is used with the python binding provision given for reference. Thanks in advance.

**Comment by berndgassmann** [comment]
We have the small python tests
https://github.com/intel/ad-rss-lib/blob/master/ad_rss/python/tests/interface_test.py
https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/python/tests/interface_test.py

And maybe some operations on data-type in the carla rss example (there the actually check calls are not done within python, though):
https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/manual_control_rss.py

Bernd.

**Comment by tvsrr** [comment]
Hello, in continuation of python implementation. When the lead vehicle is not in the sensor range of the ego vehicle and we still want RSS to evaluate every scene, what should we set the distance of seperation to be? If we set it 0; since it's not tracked by sensor it's wrong right. Are we supposed to update object parameters to None?

**Comment by berndgassmann** [comment]
Hi,

If you know the position of the other vehicle you can evaluate it, for sure. ad_rss checks are not restricted at all in terms of distance. But if you want other vehicles to be checked with distance calculations, you should provide meaningful parameters. If you only want the object-id to be visible in the RSS output list (i.e. without calculated distances) you can select the SituationType::NotRelevant (https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/impl/src/RssSceneCreator.cpp#L178)

Perhaps the following two integration examples help:

In the CARLA code:
https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/rss/RssCheck.cpp
currently all objects are ignored that are beyond 100 meter (regardless of the actual sensor range).

In the map integration code
https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/rss/RssCheck.cpp
we use the 100 meter per default as a filter, but consider in addition the stopping distance of the ego. If a vehicle is ignored here, it is presented to ad_rss check as not relevant scene (which is not actually processed within ad_rss)
https://github.com/intel/ad-rss-lib/blob/master/ad_rss_map_integration/impl/src/RssSceneCreation.cpp#L409

**Comment by berndgassmann** [comment]
I believe this can be close now.
