### ISSUE TITLE
For anyone who are having issues with python boost / cmake

### ISSUE THREAD

**Issue by Manojbhat09** [intel/ad-rss-lib#83]
For anyone who are having issues with python and boost,
Check this: https://stackoverflow.com/questions/24173330/cmake-is-not-able-to-find-boost-libraries

And for -fPIC flag:
https://stackoverflow.com/questions/39198826/what-does-the-fpic-compilation-flag-does

**Comment by Manojbhat09** [comment]
If any boost issues: https://stackoverflow.com/questions/28830653/build-boost-with-multiple-python-versions

**Comment by berndgassmann** [comment]
Thanks for providing this info so that all others having similar issues can get help here.
