### ISSUE TITLE
where is the ad/physics

### ISSUE THREAD

**Issue by ccplxx** [intel/ad-rss-lib#91]

**Comment by ccplxx** [comment]
Please help！When I read the code, but can't find the ad/physics

**Comment by berndgassmann** [comment]
Hi,
did you pull the dependencies (https://github.com/intel/ad-rss-lib/tree/master/dependencies)?
Then you can find it in 
dependencies/map/ad_physics
which currently points to this here:
https://github.com/carla-simulator/map/tree/5d0e7c49da2a20e0253c0bc3dde37094a6b7dcc5/ad_physics

Bernd.

**Comment by Dexter575** [comment]
I am curious the code in `ad_physics` codebase, the code is generated by which tool/generator? Any Idea?
Example: https://github.com/carla-simulator/map/blob/5d0e7c49da2a20e0253c0bc3dde37094a6b7dcc5/ad_physics/generated/include/ad/physics/Acceleration.hpp


Idrees.

**Comment by berndgassmann** [comment]
Hi Idrees,
the code is generated by our own internal code generator. The code generator is not open sourced and unfortunately won't be open sourced in future. 

Regards,
Bernd.
