### ISSUE TITLE
Question on code file structure layout

### ISSUE THREAD

**Issue by zwkcoding** [intel/ad-rss-lib#98]
Hi, @berndgassmann 

I noticed the file directory structure layout as follow:

```
- ad_rss
  - generated
  - impl
  - <python>
  - CMakeLists.txt
```

I guess the `generated` dir is created by some tool which is used to auto generate exporting library according `impl` dir, Am I right ?

the tool is open-source or private ? Plz let me know. Forgive my strange curiosity ：）

**Comment by berndgassmann** [comment]
Hi,

Yes, we have a model of the data type definitions with attributes as value ranges, input ranges, etc.. Out of that model the code within the generated folder is generated, so it can be used within the actual implementation.
The code generator is not open-source.
But as a user, after the install of the library you don't see any difference between generated or not generated files as they are all installed into the same folder.

**Comment by zwkcoding** [comment]
Thanks for your reply. 
I could close this issue at now.
